---
- name: configure LEMP stack
  hosts: my_vm
  become: True
  vars_files:
    - secrets.yml

  pre_tasks:
    - name: update the apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: nginx

    - role: mysql
    
    - role: php
      vars:
        php_packages:
          - php{{ php_ver }}-fpm
          - php{{ php_ver }}-mysql

    - role: ufw
      vars:
        ufw_allowed_services:
          - 'Nginx Full'
          - 'OpenSSH'

    - role: fail2ban