---
- name: install fail2ban
  apt:
    name: fail2ban
    state: present

- name: copy jail.local
  template:
    src: templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban 

- name: check fail2ban is enabled and started
  service:
    name: fail2ban
    state: started
    enabled: yes
